# to build and run use: docker-compose up --build

services:
  compression:
    build:
      context: .
      dockerfile: /tests/compressionTests/Dockerfile
  addcommand-tests:
    build:
      context: .
      dockerfile: /tests/addCommandTests/Dockerfile
  saving:
    build:
      context: .
      dockerfile: tests/SavingTextTests/Dockerfile
  file-creation:
    build:
      context: .
      dockerfile: /tests/fileCreationTests/Dockerfile
  getcommand-tests:
    build:
      context: .
      dockerfile: /tests/getCommandTests/Dockerfile
  searchcommand-tests:
    build:
      context: .
      dockerfile: /tests/searchCommandTests/Dockerfile
  input-tests:
    build:
      context: .
      dockerfile: /tests/inputTests/Dockerfile
  output-tests:
    build:
      context: .
      dockerfile: /tests/outputTests/Dockerfile
  load:
    build:
      context: .
      dockerfile: tests/loadTests/Dockerfile
  decompression:
    build:
      context: .
      dockerfile: /tests/deCompressionTests/Dockerfile
  server:
    build:
      context: .
      dockerfile: /tests/serverTests/Dockerfile
  deletefile:
    build:
      context: .
      dockerfile: /tests/deleteFIleTests/Dockerfile
  deletecommand:
    build:
      context: .
      dockerfile: /tests/deleteCommandTests/Dockerfile
      